<div class="container-fluid py-4" id="preview-forms-simple">
    <div class="row mt-lg-4 mt-2">
        <div class="col-12">
            <div class="card">
                <div class="card-body pt-0">
                    <div class="d-flex">
                        <div class="icon icon-shape icon-lg bg-gradient-info shadow text-center border-radius-xl mt-n3 ms-4">
                            <i class="material-icons opacity-10">money</i>
                        </div>
                        <h5 class="ms-3 mt-3">系統呼叫紀錄</h6>
                            <div class="ms-md-auto pe-md-3 d-flex align-items-center py-3">
                                <div class="input-group input-group-outline me-2" ng-class="(Admin.Search)?'is-filled':''">
                                    <label class="form-label">搜尋</label>
                                    <input type="text" class="form-control" ng-model="Admin.Search">
                                </div>
                                <div class="me-2 d-flex align-items-center justify-content-center" ng-click="Admin.Accounts();">
                                    <i class="material-icons opacity-10">search</i>
                                </div>
                                <div class="me-2 d-flex align-items-center justify-content-center" ng-click="Admin.Search = ''; Admin.Accounts();">
                                    <i class="material-icons opacity-10">close</i>
                                </div>
                            </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-flush" id="datatable-search">
                            <thead class="thead-light">
                                <tr class="">
                                    <th class="px-2">UniqueID</th>
                                <th class="px-2">Controller</th>
                                <th class="px-2">Action</th>
                                <th class="px-2">HTTP_HOST</th>                                
                                <th class="px-2">Status</th>                                
                                <th class="px-2">REMOTE_ADDR</th>
                                <th class="px-2">UniqueID_AccountsLoginLogs</th>                              
                                <th class="px-2">UniqueID_Accounts</th>  
                                </tr>
                                
                                
                            </thead>
                            <tbody>
                                <tr ng-repeat="item in Admin.List | filter:Admin.Search track by item.UniqueID ">
                                    <td class="text-xs font-weight-normal py-2">
                                        {{item.UniqueID}}
                                    </td>
                                    <td class="font-weight-normal">
                                        {{item.Controller}}
                                    </td>
                                    <td class="text-xs font-weight-normal">
                                        {{item.Action}}
                                    </td>
                                    <td class="text-xs font-weight-normal">
                                        {{item.HTTP_HOST}}
                                    </td>
                                    
                                    <td class="text-xs font-weight-normal">
                                        <div class="d-flex align-items-center">
                                            <button ng-click="Admin.ActionLogsModal.show();Admin.ActionLogsShow(item);" class="btn btn-icon-only btn-rounded btn-outline-success mb-0 me-2 btn-sm d-flex align-items-center justify-content-center">
                                                <i class="material-icons text-sm" aria-hidden="true" ng-show="item.finish_time">done</i>
                                            </button>
                                            <span ng-show="item.finish_time">Done</span>
                                            <span ng-show="!item.finish_time">Error</span>
                                        </div>
                                    </td>                                
                                    <td class="text-xs font-weight-normal">
                                        {{item.REMOTE_ADDR}}
                                    </td> 
                                    <td class="text-xs font-weight-normal">
                                        {{item.UniqueID_AccountsLoginLogs}}
                                    </td>
                                    <td class="text-xs font-weight-normal">
                                        {{item.UniqueID_Accounts}}
                                    </td>  
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <p class="text-center"> 共 {{Admin.ListPages.entries}} 筆資料 </p>
                    <div class="d-flex justify-content-center">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination mb-0">
                                <li class="page-item" ng-click="Admin.ListPages.PageIndex = Admin.ListPages.PageIndex - 1;Admin.Accounts();">
                                    <span class="material-icons">
                                        keyboard_arrow_left
                                    </span>
                                    <span class="sr-only">Previous</span>
                                </li>
                                <li class="page-item" ng-class="( Admin.ListPages.PageIndex == item)?'active':''" ng-repeat=" item in Admin.ListPages.List" ng-click="Admin.ListPages.PageIndex = item;Admin.ActionLogs();">
                                    <a class="page-link" ActionLogs> {{item}} </a>
                                </li>
                                <li class="page-item" ng-click="Admin.ListPages.PageIndex = Admin.ListPages.PageIndex + 1;Admin.Accounts();">
                                    <span class="material-icons">
                                        keyboard_arrow_right
                                    </span>
                                    <span class="sr-only">Next</span>
                                </li>
                            </ul>
                        </nav>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="jkanban-info-modal" style="display: none" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="h5 modal-title">Stored details</h5>
                <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="pt-4 modal-body">
                <div class="card mt-4" data-animation="true">
                    <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                        <a class="d-block blur-shadow-image">
                            <div class="card">
                                <div class="card-body p-3">
                                    <div class="d-flex mt-n2">
                                        <div class="avatar avatar-xl bg-gradient-dark border-radius-xl p-2 mt-n4">
                                            <i class="material-icons opacity-10">receipt_long</i>
                                        </div>
                                        <div class="ms-3 my-auto">
                                            <h6 class="mb-0">{{Admin.Input_ActionLogs.UniqueID}}</h6>
                                            <div class="avatar-group">
                                            </div>
                                        </div>
                                    </div>
                                    <p class="text-sm mt-3">
                                        <div>Controller: {{Admin.Input_ActionLogs.Controller}}</div>
                                        <div>Action: {{Admin.Input_ActionLogs.Action}} </div>
                                        <div>HTTP_HOST: {{Admin.Input_ActionLogs.HTTP_HOST}} </div>
                                        <div>REMOTE_ADDR: {{Admin.Input_ActionLogs.REMOTE_ADDR}} </div>
                                    </p>
                                    <hr class="horizontal dark">
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="d-flex align-items-center">
                                                <span class="btn btn-icon-only btn-rounded btn-outline-success mb-0 me-2 btn-sm d-flex align-items-center justify-content-center">
                                                    <i class="material-icons text-sm" aria-hidden="true" ng-show="Admin.Input_ActionLogs.finish_time">done</i>
                                                </span>
                                                <span ng-show="Admin.Input_ActionLogs.finish_time">Done</span>
                                                <span ng-show="!Admin.Input_ActionLogs.finish_time">Error</span>
                                            </div>
                                        </div>
                                        <div class="col-6 text-end">
                                            <h6 class="text-sm mb-0">{{Admin.Input_ActionLogs.created_time}}</h6>
                                            <p class="text-secondary text-sm font-weight-normal mb-0">Created date</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                     <div class="card-body text-center"> 
                        <p class="mb-0">
                        {{Admin.Input_ActionLogs.Return_JSON}}                            
                        </p>
                    </div>
                    <div class="card-body text-center"> 
                        <p class="mb-0">
                        {{Admin.Input_ActionLogs.PostData_JSON}}                            
                        </p>
                    </div>
                    <hr class="dark horizontal my-0">
                    <div class="card-footer d-flex">
                        <p class="font-weight-normal my-auto">$ {{Admin.Input_ActionLogs.cost_num}}</p>
                        <i class="material-icons position-relative ms-auto text-lg me-1 my-auto">place</i>
                        <p class="text-sm my-auto"> {{Admin.Input_ActionLogs.REMOTE_ADDR}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>