<nav ng-controller="NavController as Nav" class="navbar navbar-main navbar-expand-lg position-sticky mt-4 top-1 px-0 mx-4 shadow-none border-radius-xl z-index-sticky" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">        
        <div class="sidenav-toggler sidenav-toggler-inner d-xl-block d-none ">
          <a href="javascript:;" class="nav-link text-body p-0">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </a>
        </div>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            
          </div>
          <ul class="navbar-nav  justify-content-end">
                       
            <li class="nav-item px-3" ng-click="Nav.Logout()">
              <a class="nav-link text-body p-0" >
                <i class="material-icons fixed-plugin-button-nav cursor-pointer">logout</i>
              </a>
            </li>            
          </ul>
        </div>
      </div>
      <script>
        adonis.controller('NavController', ['sharedData', '$scope', '$http',function(sharedData,$scope, $http) {
              var Nav = this;
              if (location.pathname == "/logout") location.href = '';
              Nav.ReDirect = function(ReDirect) {
                  sharedData.ReDirect(ReDirect);
              }
              Nav.Logout = function() {
                  sharedData.Logout();
              }
          }]);
      </script>
    </nav>