<!--
=========================================================
* Material Dashboard 2 PRO - v3.0.2
=========================================================

* Product Page:  https://www.creative-tim.com/product/material-dashboard-pro 
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>  
  <title>
    註冊信件
  </title>
  <?php echo $header; ?>
</head>

<body class="bg-gray-200">
  <!-- Extra details for Live View on GitHub Pages -->
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NKDMSK6" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->

  <!-- End Navbar -->
  <main class="main-content  mt-0">
    <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container my-auto">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-7 mx-auto">
            <div class="card">
              <div class="card-header text-center py-0">
                <div class="mt-n5">
                  <img class="avatar avatar-xxl shadow-lg" alt="Image placeholder" src="icon.jpg">
                </div>
              </div>
              <div class="card-body text-center">
                <h4 class="mb-0 font-weight-bolder">Adonis.tw</h4>
                <p class="mb-4">前往網站輸入認證簡訊碼，已完成本服務註冊。</p>


                <div class="text-center">

                  <a href="http://account.adonis.tw/Auth/SignToken/<?php echo $UniqueID; ?>/<?php echo $Token; ?>" target="_blank">
                    <button id="SignEmail_submit" type="button" class="btn btn-lg bg-gradient-dark mt-4 mb-0">SignEmail</button>
                  </a>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

</body>

</html>