<div class="container-fluid py-4" id="preview-forms-simple">
    <div class="row mt-lg-4 mt-2">
        <div class="col-12">
            <div class="card">
                <div class="card-body pt-0">
                    <div class="d-flex">
                        <div class="icon icon-shape icon-lg bg-gradient-info shadow text-center border-radius-xl mt-n3 ms-4">
                            <i class="material-icons opacity-10">money</i>
                        </div>
                        <h5 class="ms-3 mt-3" ng-click="Admin.BankData();">OneDalla</h6>
                            <div class="ms-md-auto pe-md-3 d-flex align-items-center py-3">
                                <div class="input-group input-group-outline me-2" ng-class="(Admin.Search)?'is-filled':''">
                                    <label class="form-label">搜尋: 訂單號,商戶號,交易日期,銀行帳號,狀態</label>
                                    <input type="text" class="form-control" ng-model="Admin.Search">
                                </div>
                                <div class="me-2 d-flex align-items-center justify-content-center" ng-click="Admin.OneDalla();">
                                    <i class="material-icons opacity-10">search</i>
                                </div>
                                <div class="me-2 d-flex align-items-center justify-content-center" ng-click="Admin.Search = ''; Admin.OneDalla();">
                                    <i class="material-icons opacity-10">close</i>
                                </div>
                            </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-flush" id="datatable-search">
                            <thead class="thead-light">
                                <tr class="">                                    
                                    <th class="px-2">訂單號</th>
                                    <th class="px-2">交易金額</th>
                                    <th class="px-2">交易日期</th>
                                    <th class="px-2">交易對象</th>
                                    <th class="px-2">狀態</th>

                                    <th class="px-2">銀行代碼</th>
                                    <th class="px-2">銀行帳號</th>

                                    <th class="px-2" colspan="4">銀行匯款資料</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="item in Admin.OneDalla_List | filter:Admin.Search track by $index " ng-class="(item.BankCount > 1 )?'text-danger':''">
                                    
                                    <td class="text-xs font-weight-normal py-2">
                                        {{item.order_number}}
                                    </td>                                  
                                    <td class="text-xs font-weight-normal py-2">
                                        {{item.Amount}}
                                    </td>
                                    <td class="text-xs font-weight-normal py-2">
                                        {{item.Amount_date}}
                                    </td>
                                    <td class="text-xs font-weight-normal py-2">
                                        {{item.Payee_Name}}
                                    </td>
                                    <td class="text-xs font-weight-normal py-2">
                                        {{item.status}}
                                    </td>

                                    <td class="text-xs font-weight-normal py-2">
                                        {{item.Bank_Code}}
                                    </td>
                                    <td class="text-xs font-weight-normal py-2">
                                        {{item.Bank_account}}
                                    </td>
                                   
                                   
                                    <td class="text-xs font-weight-normal py-2">
                                        <span ng-if="item.BankData">{{item.BankData.created_time}}</span>
                                    </td>
                                    <td class="text-xs font-weight-normal py-2">
                                        
                                        <span ng-if="item.BankData">{{item.BankData.Bank_accountAs}}</span>
                                    </td>
                                    <td class="text-xs font-weight-normal py-2">
                                    <span ng-if="item.BankData">{{item.BankData.payout}}</span>
                                    </td>
                                    <td class="text-xs font-weight-normal py-2">
                                    <span ng-if="item.BankData">{{item.BankData.Mark}}{{item.BankData.Remark}}</span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <p class="text-center"> 共 {{Admin.ListPages.entries}} 筆資料 </p>
                    <div class="d-flex justify-content-center">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination mb-0">
                                <li class="page-item" ng-click="Admin.ListPages.PageIndex = Admin.ListPages.PageIndex - 1;Admin.OneDalla();">
                                    <span class="material-icons">
                                        keyboard_arrow_left
                                    </span>
                                    <span class="sr-only">Previous</span>
                                </li>
                                <li class="page-item" ng-class="( Admin.ListPages.PageIndex == item)?'active':''" ng-repeat=" item in Admin.ListPages.List" ng-click="Admin.ListPages.PageIndex = item;Admin.OneDalla();">
                                    <a class="page-link" ActionLogs> {{item}} </a>
                                </li>
                                <li class="page-item" ng-click="Admin.ListPages.PageIndex = Admin.ListPages.PageIndex + 1;Admin.OneDalla();">
                                    <span class="material-icons">
                                        keyboard_arrow_right
                                    </span>
                                    <span class="sr-only">Next</span>
                                </li>
                            </ul>
                        </nav>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="OneDallaModal" style="display: none" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="h5 modal-title">Stored details</h5>
                <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="pt-4 modal-body">
                <div class="card mt-4" data-animation="true">
                    <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                        <a class="d-block blur-shadow-image">
                            <div class="card">
                                <div class="card-body p-3">
                                    <div class="d-flex mt-n2">
                                        <div class="avatar avatar-xl bg-gradient-dark border-radius-xl p-2 mt-n4">
                                            <i class="material-icons opacity-10">person_add</i>
                                        </div>
                                        <div class="ms-3 my-auto">
                                            <h6 class="mb-0">{{Admin.StoredChange.UniqueID}}</h6>
                                            <div class="avatar-group">
                                            </div>
                                        </div>
                                    </div>
                                    <p class="text-sm mt-3">
                                        <div> 帳號 : {{Admin.StoredChange.account}} </div>
                                        <div> 密碼 : {{Admin.StoredChange.password}} </div>
                                    </p>
                                </div>
                            </div>
                        </a>
                    </div>

                    <hr class="dark horizontal my-0">
                    <div class="card-footer d-flex">

                        <i class="material-icons position-relative ms-auto text-lg me-1 my-auto">place</i>
                        <p class="text-sm my-auto"> {{Admin.StoredChange.REMOTE_ADDR}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>